name: Deploy Weather Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs  # Make sure your index.html and assets are inside this folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
